### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by GGeorgieva** [Team-Doldur/PhotoAlbum#1]
1. Да качим едно category с един албум снимки в базата, за да е по лесно да си визуализираме кода.
   Category -> Album -> Pictures -> Comments
             -> Comments
   
   Като отделни класове с релации ли ще ги направим или категорията ще държи 
   масив от албуми с масив от снимки и масив от коментари?
2.  Front Page:
   Get Categories
   Get Best Albums
   Get Random Albums
   
   -- HTML View
   -- event listeners
3.  Category page: 
   get Category Description;
   get Albums Names And Rating;
   
   -- HTML View
   -- event listeners
4.  Album page:
   Get Album Properties;
   Get Album Pictures;
   Get Album Comments?
   POST Comment;
   POST Add Rating;
   
   -- HTML View
   -- event listeners
   
   Picture page:
   Get Picture image
   (Ако вече са изтеглени в thumbnail формат,
    трябва ли да се прави тук нова заявка или просто се обработва със CSS?)
   Get Picture Rating
   Get Picture Comments
   POST Comment;
   POST Add Rating;
   
   -- HTML View
   -- eventListeners
5. Manage Albums:
   POST Album;
   POST Picture;
   DELETE Album;
   DELETE Picture
6. Brouse.
7. CSS.
   7....Register User and user specific functionality.

Можем да си разделим задачите по модели, като HTML View move да се съдържа във всеки модел или всеки да напише по два модула - един за модела си и един за неговото view.

**Comment by iliankostov** [comment]
Moved to Milestone
